### PR TITLE
Change the color of text

### PR DESCRIPTION
**Pull request by rossieeissor**
I changed the color of tabs text.

### CODE REVIEW

**Comment by rohansx** [comment]
Please request to get assigned in the issues tab first so that i can assign you and also while making PR add "fix #issue_no"

**Comment by rohansx** [comment]
Please provide screenshot of the changes you've made.

**Comment by rossieeissor** [comment]
image

**Comment by rohansx** [comment]
I need the screenshot of changes you've made on web application, not the screenshot of code. 
Run it on localhost and then screenshot it

**Comment by rossieeissor** [comment]
image

**Pull request closed without merging**
