### PR TITLE
CONTRIBUTING.md

### LINKED ISSUE #4: Create CONTRIBUTING.md file
Create CONTRIBUTING.md file for this repository

- The project is built using reactjs, so add installation part according to that

### PR DESCRIPTION
**Pull request by tan911**
fixes #4 Added contributing file:
 - step by step instructions also installations

### CODE REVIEW

**Review by rohansx — CHANGES_REQUESTED** [review]
Replace username of organization instead of "your-username". 
Change line no 13,14

**Comment by rohansx** [comment]
Please request to assign yourself for that issue in the issues tab, so that i can assign you this task.

**Comment by rohansx** [comment]
Also, while submitting PR, add "fix #issue_no" in the description

**Comment by tan911** [comment]
Noted, I'll fix it.

**Review by rohansx — APPROVED** [review]
lgtm

**Pull request merged**
